#!/bin/bash
# Query service by serial number for configuration values

usage ()
{
  echo "usage: $0 SERIAL"
  exit 1
}

if [ $# -gt 0 ];
then
  if [ $1 == "-h" ];
  then
    usage
    exit
  fi
fi

# Attempt to read serial from stdin and fallback to arg
if [ -p /dev/stdin ]; then
  read serial
elif [ -n "$1" ]; then
  serial="$1"
fi

validate='https?://*'

if [ -z "${DEVICE_LOOKUP_SERVER}" ];
then
  server_url="$(snapctl get url 2>/dev/null)"
  # Validate it
  if [[ ! $server_url =~ $validate ]]; then
    echo "DEVICE_LOOKUP_SERVER not set"
    exit 1
  fi
else
  server_url=${DEVICE_LOOKUP_SERVER}
  if [[ ! $server_url =~ $validate ]]; then
    echo "Invalid DEVICE_LOOKUP_SERVER URL $server_url"
    exit 1
  fi
fi

OUT=$(curl -s -X GET $server_url/autoinstall/$serial)
echo $OUT | yq
