name: device-config-client
version: git
summary: Device Config Client
description: Generate device configuration from Device Lookup Service
base: core24
grade: stable
confinement: strict
platforms:
  amd64:

apps:
  gen-landscape-conf:
    command: bin/gen-landscape-conf
    plugs:
      - network
      - home
  bios:
    command: bin/bios
    plugs:
      - network
      - home
  add-bios:
    command: bin/add-bios
    plugs:
      - network
      - home
  device:
    command: bin/device
    plugs:
      - network
      - home
  add-device:
    command: bin/add-device
    plugs:
      - network
      - home
  autoinstall:
    command: bin/autoinstall
    plugs:
      - network
      - home
  add-autoinstall:
    command: bin/add-autoinstall
    plugs:
      - network
      - home
  get-serial:
    command: bin/get-serial
    plugs:
      - hardware-observe
  get-product-name:
    command: bin/get-product-name
    plugs:
      - hardware-observe

parts:
  device-config-client:
    plugin: dump
    source: .
    build-packages:
      - git
    stage-packages:
      - curl
      - jq
    stage-snaps:
      - yq
    organize:
      gen-landscape-conf: bin/
      device: bin/
      add-device: bin/
      bios: bin/
      add-bios: bin/
      autoinstall: bin/
      add-autoinstall: bin/
      get-serial: bin/
      get-product-name: bin/
